repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements
        language_version: python3

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        language_version: python3
        files: ^src/

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args:
          - --py311-plus

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        files: ^src/
        args:
          - --config-file
          - mypy.ini
          - --install-types
          - --non-interactive
          - --explicit-package-bases

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        files: src
        args:
          - src/
          - --target-version=py311
          - --check
          - --verbose
          - --diff
          - --color
        exclude: ^.cache/

  - repo: local
    hooks:
      - id: export-requirements
        name: Export requirements.txt
        language: system
        pass_filenames: false
        entry: poetry export -f requirements.txt --output requirements.txt
        files: ^(pyproject.toml|poetry.lock)$
